[SRN-101] Set Customer Reference same as PO reference on shipping label
CaseyWilder/SIRENA pull request #26
Opened 2021-08-11 21:29 UTC by thangnguyen-novobi

2021-08-16 00:39 UTC, tiennguyen-novobi requested changes

2021-08-16 00:39 UTC, tiennguyen-novobi commented on novobi_addons/sirena_fedex/models/delivery_fedex.py
> +                po_number=po_number,
You replace `reference`, right?
Instead of overriding this whole method, may we only inherit `_add_package` and set `reference = po_number` before calling `super()`? Also need to check other cases before using this way.

2021-08-16 00:39 UTC, tiennguyen-novobi commented on novobi_addons/sirena_fedex/models/delivery_fedex.py
> +                    confirmation=picking.fedex_shipping_confirmation,
Same to above

2021-08-17 05:19 UTC, thangnguyen-novobi commented
Issues resolved

2021-08-17 05:46 UTC, tiennguyen-novobi approved these changes

2021-08-17 05:46 UTC, merged